const randomData = [
  {
    activity: "Shred old documents you don't need anymore",
    type: 'busywork',
    participants: 1,
    price: 0,
    link: '',
    key: '2430066',
    accessibility: 0,
  },
  {
    activity: 'Do yoga',
    type: 'recreational',
    participants: 1,
    price: 0,
    link: '',
    key: '4688012',
    accessibility: 0.9,
  },
  {
    activity: 'Take a bubble bath',
    type: 'relaxation',
    participants: 1,
    price: 0.15,
    link: '',
    key: '2581372',
    accessibility: 0.1,
  },
  {
    activity: "Clean out your closet and donate the clothes you've outgrown",
    type: 'charity',
    participants: 1,
    price: 0,
    link: '',
    key: '9026787',
    accessibility: 0.1,
  },
  {
    activity: 'Explore the nightlife of your city',
    type: 'social',
    participants: 1,
    price: 0.1,
    link: '',
    key: '2237769',
    accessibility: 0.32,
  },
  {
    activity: 'Start a daily journal',
    type: 'relaxation',
    participants: 1,
    price: 0,
    link: '',
    key: '8779876',
    accessibility: 0,
  },
  {
    activity: 'Surprise your significant other with something considerate',
    type: 'social',
    participants: 1,
    price: 0,
    link: '',
    key: '6204657',
    accessibility: 0,
  },
  {
    activity: 'Do a jigsaw puzzle',
    type: 'recreational',
    participants: 1,
    price: 0.1,
    link: 'https://en.wikipedia.org/wiki/Jigsaw_puzzle',
    key: '8550768',
    accessibility: 1,
  },
  {
    activity: "Mow your neighbor's lawn",
    type: 'charity',
    participants: 1,
    price: 0,
    link: '',
    key: '1303906',
    accessibility: 0.2,
  },
  {
    activity: 'Compliment someone',
    type: 'social',
    participants: 2,
    price: 0,
    link: '',
    key: '9149470',
    accessibility: 0,
  },
  {
    activity: 'Draft your living will',
    type: 'busywork',
    participants: 1,
    price: 0,
    link: 'https://www.investopedia.com/terms/l/livingwill.asp',
    key: '2360432',
    accessibility: 0.5,
  },
  {
    activity: 'Draw and color a Mandala',
    type: 'relaxation',
    participants: 1,
    price: 0.05,
    link: 'https://en.wikipedia.org/wiki/Mandala',
    key: '4614092',
    accessibility: 0.1,
  },
  {
    activity: 'Patronize a local independent restaurant',
    type: 'recreational',
    participants: 1,
    price: 0.2,
    link: '',
    key: '5319204',
    accessibility: 0.1,
  },
  {
    activity: 'Have a picnic with some friends',
    type: 'social',
    participants: 3,
    price: 0.1,
    link: '',
    key: '6813070',
    accessibility: 0.1,
  },
  {
    activity: 'Plan a trip to another country',
    type: 'recreational',
    participants: 1,
    price: 0,
    link: '',
    key: '5554727',
    accessibility: 0,
  },
  {
    activity: 'Have a paper airplane contest with some friends',
    type: 'social',
    participants: 4,
    price: 0.02,
    link: '',
    key: '8557562',
    accessibility: 0.05,
  },
  {
    activity: 'Take your dog on a walk',
    type: 'relaxation',
    participants: 1,
    price: 0,
    link: '',
    key: '9318514',
    accessibility: 0.2,
  },
  {
    activity: 'Learn how to play a new sport',
    type: 'recreational',
    participants: 1,
    price: 0.1,
    link: '',
    key: '5808228',
    accessibility: 0.2,
  },
  {
    activity: 'Memorize the fifty states and their capitals',
    type: 'education',
    participants: 1,
    price: 0,
    link: '',
    key: '4179309',
    accessibility: 0,
  },
  {
    activity: 'Make a bucket list',
    type: 'busywork',
    participants: 1,
    price: 0,
    link: '',
    key: '2735499',
    accessibility: 0,
  },
  {
    activity: 'Learn and play a new card game',
    type: 'recreational',
    participants: 1,
    price: 0,
    link: 'https://www.pagat.com',
    key: '9660022',
    accessibility: 0,
  },
  {
    activity: 'Have a paper airplane contest with some friends',
    type: 'social',
    participants: 4,
    price: 0.02,
    link: '',
    key: '8557562',
    accessibility: 0.05,
  },
  {
    activity: 'Do a jigsaw puzzle',
    type: 'recreational',
    participants: 1,
    price: 0.1,
    link: 'https://en.wikipedia.org/wiki/Jigsaw_puzzle',
    key: '8550768',
    accessibility: 1,
  },
  {
    activity: 'Go on a fishing trip with some friends',
    type: 'social',
    participants: 3,
    price: 0.4,
    link: '',
    key: '3149232',
    accessibility: 0.4,
  },
  {
    activity: 'Play a video game',
    type: 'recreational',
    participants: 1,
    price: 0,
    link: '',
    key: '5534113',
    accessibility: 0,
  },
]

export default randomData
